language: python

python:
- '2.7'
- '3.5'

install:
- pip install -r requirements.pip
- pip install coveralls

script:
  - cd neuropy
  - coverage run imagersite/manage.py test imagersite

after_success:
  - coveralls

notifications:
  email: false
