language: python

python:
- '2.7'
- '3.5'

services:
  - postgresql

before_script:
  - psql -c "create database hikinglog;" -U postgres

install:
- pip install -r requirements.pip
- pip install coveralls

script:
  - python hikinglog/manage.py migrate
  - coverage run hikinglog/manage.py test hikinglog

after_success:
  - coveralls

notifications:
  email: false
